### ISSUE TITLE
feat: cli arg parser

### ISSUE THREAD

**Issue by kruserr** [kruserr/i6#1]
CLI arg parser, that is fit for this project.

## Tasks
- [ ] can handle 2-3 nested commands
- [ ] can handle flags shared between nested commands
- [ ] maintainable and extensible to 10+ commands with 4+ nested commands each
- [ ] clean public api
